DEPS: unpin Matplotlib and cratopy
matplotlib/cheatsheets pull request #107
Opened 2022-02-23 21:40 UTC by tacaswell

2022-02-24 03:23 UTC, jimustafa commented
I think the matplotlib version _should_ be pinned and match the version tag that is shown on the cheatsheets. That way, the cheatsheets will be built with a definite version of matplotlib. The matplotlib version can be bumped, along with version tag on cheatsheets, using the `bump2version` utility.

Yes, `make check` fails because the installed matplotlib version does not match the cheatsheets version tag.

2022-02-24 17:35 UTC, tacaswell commented
Fair enough.

I also added a section to the read me documenting how to use `bump2version`.

2022-02-25 01:55 UTC, jimustafa requested changes

2022-02-25 01:55 UTC, jimustafa commented on README.md
> +The version of Matplotlib is hard-coded a number of places throughout the
hard-coded _in_ a number of places...

2022-02-25 01:55 UTC, jimustafa commented on README.md
> +$ bump2release --new-version x.y.Z patch
should this just be `bump2version patch`

2022-02-25 01:55 UTC, jimustafa commented on README.md
> +$ bump2release --new-version x.Y.0 minor
should this just be `bump2version minor`

2024-01-30 11:33 UTC, dstansby commented
I'm going to close this in favour of other more recent PRs to bump the MPL version.

2024-01-30 11:33 UTC, closed without merging