traduz dicas
matplotlib/cheatsheets pull request #132
Opened 2023-05-06 15:39 UTC by giovana-morais

2023-05-08 12:10 UTC, timhoffm requested changes
Thanks for the contribution!

Please do not overwrite the existing english versions.

Overall, we have to come up with a scheme how to manage translations:

- README: I think the best the pattern shown in https://github.com/tiimgreen/github-cheat-sheet: `README.[lang].md` files and a link *Read this in other languages* in the main README.
- Content: Please make new files for the translated handouts as well.

An unresolved problem is keeping translations synchronous and up to date.

2023-05-08 16:46 UTC, giovana-morais commented
@timhoffm thanks for jumping in! 
I overwrote the file because I thought it would stay only in this fork, but I like your idea much better. I'll create the new files for both README and the handouts.

regarding keeping the translations open to date, I thought about maybe automatically creating an issue for the translation repository whenever we have new PRs merged in the official one, via the CI tool. not sure if it's the best approach, but I think it will give us visibility. :thinking:

2023-05-24 12:47 UTC, melissawm reviewed
This is looking great, thank you so much @giovana-morais !

2023-05-24 12:47 UTC, melissawm commented on README.pt-br.md
> +do `matplotlib`.
```suggestion
não-oficial visa tornar as dicas mais acessíveis para os usuários e usuárias
```
How about using gender-neutral language here? (I also am used to "a Matplotlib" as it is a library (uma biblioteca) but there's no right or wrong here 😅 

```suggestion
não-oficial visa tornar as dicas mais acessíveis para pessoas que usam a Matplotlib.
```

2023-05-24 12:47 UTC, melissawm commented on README.pt-br.md
> +* `fonts/pacifico/*`         : See https://fonts.google.com/download?family=Pacifico
```suggestion
* `fonts/roboto/*`           : Veja https://fonts.google.com/specimen/Roboto
                                ou https://github.com/googlefonts/roboto/tree/master/src/hinted
* `fonts/roboto-slab/*`      : Veja https://fonts.google.com/specimen/Roboto+Slab
                                ou https://github.com/googlefonts/robotoslab/tree/master/fonts/static
* `fonts/source-code-pro/*`  : Veja https://fonts.google.com/specimen/Source+Code+Pro
                                ou https://github.com/adobe-fonts/source-code-pro/tree/release/OTF
* `fonts/source-sans-pro/*`  : Veja https://fonts.google.com/specimen/Source+Sans+Pro
                                ou https://github.com/adobe-fonts/source-sans-pro/tree/release/OTF
* `fonts/source-serif-pro/*` : Veja https://fonts.google.com/specimen/Source+Serif+Pro
                                ou https://github.com/adobe-fonts/source-serif-pro/tree/release/OTF
* `fonts/eb-garamond/*`      : Veja https://bitbucket.org/georgd/eb-garamond/src/master
* `fonts/pacifico/*`         : Veja https://fonts.google.com/download?family=Pacifico
```

2023-05-24 12:47 UTC, melissawm commented on README.pt-br.md
> +* `fonts/pacifico/*`         : See https://fonts.google.com/download?family=Pacifico
```suggestion
* `fonts/roboto/*`           : Veja https://fonts.google.com/specimen/Roboto
                                ou https://github.com/googlefonts/roboto/tree/master/src/hinted
* `fonts/roboto-slab/*`      : Veja https://fonts.google.com/specimen/Roboto+Slab
                                ou https://github.com/googlefonts/robotoslab/tree/master/fonts/static
* `fonts/source-code-pro/*`  : Veja https://fonts.google.com/specimen/Source+Code+Pro
                                ou https://github.com/adobe-fonts/source-code-pro/tree/release/OTF
* `fonts/source-sans-pro/*`  : Veja https://fonts.google.com/specimen/Source+Sans+Pro
                                ou https://github.com/adobe-fonts/source-sans-pro/tree/release/OTF
* `fonts/source-serif-pro/*` : Veja https://fonts.google.com/specimen/Source+Serif+Pro
                                ou https://github.com/adobe-fonts/source-serif-pro/tree/release/OTF
* `fonts/eb-garamond/*`      : Veja https://bitbucket.org/georgd/eb-garamond/src/master
* `fonts/pacifico/*`         : Veja https://fonts.google.com/download?family=Pacifico
```

2023-05-24 12:47 UTC, melissawm commented on README.pt-br.md
> +criar o seguinte `$HOME/.config/fontconfig/fonts.conf` (veja [aqui](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html)):
```suggestion
criar o arquivo `$HOME/.config/fontconfig/fonts.conf` com o seguinte conteúdo (veja [aqui](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html)):
```

2023-05-24 12:47 UTC, melissawm commented on handout-beginner.pt-br.tex
> +Matplotlib é uma biblioteca para gerar plots em 2D em Python. Foi desenhado
```suggestion
Matplotlib é uma biblioteca para gerar plots em 2D em Python. Foi criada
```

2023-05-24 12:47 UTC, melissawm commented on handout-beginner.pt-br.tex
> +cores, marcadores, grossura e estilo de linhas, ticks e rótulos de ticks,
Será que a gente consegue encontrar uma tradução para "ticks"?

2023-05-24 12:47 UTC, melissawm commented on handout-beginner.pt-br.tex
> +          Matplotlib \textcolor{orange}{\mdseries for beginners}}
```suggestion
          Matplotlib \textcolor{orange}{\mdseries para iniciantes}}
```

2023-05-24 19:08 UTC, giovana-morais commented on README.pt-br.md
> +* `fonts/pacifico/*`         : See https://fonts.google.com/download?family=Pacifico
nossa, eu nem tinha visto esses pedaços hahahaha

2023-05-24 19:10 UTC, giovana-morais commented on README.pt-br.md
> +do `matplotlib`.
por mim ok usar como "a matplotlib" no sentido de biblioteca. eu sempre pensei como "o módulo"

2023-05-24 20:18 UTC, giovana-morais commented on handout-beginner.pt-br.tex
> +cores, marcadores, grossura e estilo de linhas, ticks e rótulos de ticks,
pois é, essa é uma questão que eu e a @R-it-a estávamos discutindo bastante e acho que você pode nos ajudar. tem alguns termos como "ticks", "axis" e "plot" que são muito ligados aos nomes das funções disponíveis na biblioteca. aí a nossa dúvida era: se a gente traduz, será que fica mais difícil de associar o nome ao comando?

2023-07-13 19:53 UTC, giovana-morais commented
@timhoffm any suggestions on how to proceed with the Makefile? I thought about creating something like "make translation <language>", but I'm open to suggestions

2023-07-19 14:40 UTC, melissawm approved these changes
Looking great - some minor comments but I'm approving since the contents in general are done. Obrigada @giovana-morais !!

2023-07-19 14:40 UTC, melissawm commented on README.pt-br.md
> +Folheto iniciante [(download pdf)](https://matplotlib.org/cheatsheets/handout-beginner.pdf) | Folheto intermediário[(download pdf)](https://matplotlib.org/cheatsheets/handout-intermediate.pdf) | Folh
```suggestion
Folheto iniciante [(download pdf)](https://matplotlib.org/cheatsheets/handout-beginner.pdf) | Folheto intermediário [(download pdf)](https://matplotlib.org/cheatsheets/handout-intermediate.pdf) | Folheto de dicas [(download pdf)](https://matplotlib.org/cheatsheets/handout-tips.pdf)
```

2023-07-19 14:40 UTC, melissawm commented on README.pt-br.md
> +# Para contribuídores das dicas
```suggestion
# Para contribuidores das dicas
```

2023-07-19 14:40 UTC, melissawm commented on README.pt-br.md
> +1. Você precisa criar um repositório `fonts`com:
```suggestion
1. Você precisa criar um repositório `fonts` com:
```

2023-07-19 14:40 UTC, melissawm commented on handout-beginner.pt-br.tex
> +Matplotlib é uma biblioteca para gerar plots em 2D em Python. Foi criada
I am not sure if this is the original wording, but you can also do 3D plots in Matplotlib - maybe this should be updated?

2023-07-19 14:40 UTC, melissawm commented on handout-intermediate.pt-br.tex
> +%As well as nice colormaps (viridis an magma):\\
Is this line also commented out in the original?

2023-07-19 14:56 UTC, giovana-morais commented on handout-intermediate.pt-br.tex
> +%As well as nice colormaps (viridis an magma):\\
yes, [it is!](https://github.com/matplotlib/cheatsheets/blob/898944be6f572ab82f03900b8b7e958e00c29c59/handout-intermediate.tex#L180-L182).

2023-07-19 14:57 UTC, giovana-morais commented on handout-beginner.pt-br.tex
> +Matplotlib é uma biblioteca para gerar plots em 2D em Python. Foi criada
we followed the [original](https://github.com/matplotlib/cheatsheets/blob/898944be6f572ab82f03900b8b7e958e00c29c59/handout-beginner.tex#L74). should I add the 3D part in both documents?

2023-07-19 15:34 UTC, melissawm commented on handout-beginner.pt-br.tex
> +Matplotlib é uma biblioteca para gerar plots em 2D em Python. Foi criada
That would be my suggestion!

2023-10-10 04:28 UTC, giovana-morais commented
@timhoffm i was thinking that the specific Makefile for the translation handouts could be done in the PyLadies repo instead of here. can you review the PR as it is?

2023-10-10 18:01 UTC, melissawm approved these changes
@timhoffm as far as the text goes, I'm happy with it!

2023-10-30 21:17 UTC, giovana-morais commented
I'll close this PR because I already merged the changes on the PyLadies Brasil fork. It makes more sense to keep it separate, so we can change the Makefile to generate the translated document instead of the original one and we have more freedom to use the translated version of the README as the original. 
@melissawm thank you for the help reviewing the translation and thanks @timhoffm for the guidance in the translation patterns! Later I can open a new PR with only an update on the README pointing to the PyLadies Brasil translation for Portuguese.

Obrigada!

2023-10-30 21:17 UTC, closed without merging